@startuml
'https://plantuml.com/sequence-diagram

autonumber

activate Main.Floor
activate Main.EventQueue
activate Main.Scheduler
activate Main.Elevator
loop while processedEvents < maxEvents
    Main.Floor -> Main.Floor: processFile(file: File)
    Main.Floor -> Main.Floor: processInput(input: String)
    Main.Floor --> Main.EventQueue: setFloorRequest(event: Main.ElevatorEvent)

    loop while processedEvents < maxEvents
        Main.Scheduler --> Main.EventQueue: ReadFloorRequest()
        Main.EventQueue -> Main.Scheduler: getFloorRequest(): Main.ElevatorEvent
        alt floorRequestToBeProcessed != null
            Main.Scheduler -> Main.Scheduler: processFloorRequest()
            Main.Scheduler --> Main.EventQueue: sendElevatorRequest()
        end
    end

    loop while processedEvents < maxEvents
        Main.Elevator --> Main.EventQueue: getElevatorRequest()
        alt elevatorRequest.isEmpty
            Main.EventQueue --> Main.Elevator: event: Main.ElevatorEvent
        end
        alt event != null
            Main.Elevator -> Main.Elevator: floorRequested()
        end
    end
end

destroy Main.Floor
destroy Main.EventQueue
destroy Main.Elevator
destroy Main.Scheduler
@enduml